import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
LAUNCHER = REPO / "factory_flow_start.command"
SERVER = REPO / "server.py"


class FlowFactoryLauncherRegressionTest(unittest.TestCase):
    def test_launcher_runs_server_in_visible_terminal(self):
        script = LAUNCHER.read_text(encoding="utf-8")
        self.assertIn('PORT="${FLOWFACTORY_PORT:-8765}"', script)
        self.assertIn('URL="http://127.0.0.1:$PORT/"', script)
        self.assertIn("curl --noproxy '*' -fsS", script)
        self.assertIn('REPO="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"', script)
        self.assertIn('FLOWFACTORY_DATA_DIR="$DATA_DIR" AUTOMONEY_NO_BROWSER=1', script)
        self.assertNotIn("/Users/gl/", script)
        self.assertNotIn("launchctl", script)

    def test_server_can_skip_automatic_browser_open(self):
        server = SERVER.read_text(encoding="utf-8")
        self.assertIn("AUTOMONEY_NO_BROWSER", server)
        self.assertIn("webbrowser.open(url)", server)

    def test_runtime_data_is_separate_from_program_files(self):
        server = SERVER.read_text(encoding="utf-8")
        self.assertIn("FLOWFACTORY_DATA_DIR", server)
        self.assertIn("DATA_DIR / 'workflows.json'", server)
        self.assertIn("SAFE_CONTENT_ROOT = DATA_DIR / 'outputs'", server)
        self.assertIn("migrate_legacy_content_root()", server)

    def test_release_installer_supports_updates_and_checksums(self):
        installer = (REPO / "scripts" / "install.sh").read_text(encoding="utf-8")
        self.assertIn("FLOWFACTORY_UPDATE_BASE_URL", installer)
        self.assertIn("latest.json", installer)
        self.assertIn("hashlib.sha256", installer)
        self.assertNotIn("GH_TOKEN", installer)
        self.assertNotIn("github.com", installer)
        self.assertIn("flowfactory [start|stop|update|uninstall|version]", installer)
        self.assertIn('ln -sfn "$TARGET" "$INSTALL_ROOT/current"', installer)
        self.assertIn("操作面板：http://127.0.0.1:8765/", installer)
        self.assertIn('"$BIN_DIR/flowfactory" start', installer)
        self.assertIn("stop_running_service", installer)
        self.assertIn("FLOWFACTORY_INSTALL_OPEN_BROWSER=0", installer)
        self.assertIn("FLOWFACTORY_NO_OPEN_BROWSER", installer)
        self.assertIn("-iTCP:8765 -sTCP:LISTEN", installer)
        self.assertIn("11 12 13 14 15 16 17 18 19 20", installer)
        self.assertIn("suspend_autostart", installer)
        self.assertIn("wait_for_version", installer)
        self.assertIn("新版健康检查失败，已自动回退上一版本", installer)
        self.assertIn("report_install_success", installer)
        self.assertIn("FLOWFACTORY_DISABLE_TELEMETRY", installer)
        self.assertIn("/v1/telemetry/install", installer)

    def test_service_health_monitor_and_safe_release_preflight_are_present(self):
        html = (REPO / "index.html").read_text(encoding="utf-8")
        updater = (REPO / "updater.py").read_text(encoding="utf-8")
        self.assertIn("setInterval(monitorServiceHealth,5000)", html)
        self.assertIn("Flow Factory 服務已中斷，系統正在嘗試自動恢復", html)
        self.assertIn("def validate_release(target", updater)
        self.assertIn("新版启动检查失败", updater)

    def test_uninstaller_preserves_data_by_default(self):
        uninstaller = (REPO / "scripts" / "uninstall.sh").read_text(encoding="utf-8")
        self.assertIn('rm -rf "$INSTALL_ROOT/versions" "$INSTALL_ROOT/current" "$INSTALL_ROOT/run"', uninstaller)
        self.assertIn('if [ "$PURGE" -eq 1 ]', uninstaller)
        self.assertIn('read -r answer', uninstaller)
        self.assertNotIn('rm -rf "$INSTALL_ROOT"\nelse', uninstaller)

    def test_settings_page_exposes_safe_update_controls(self):
        html = (REPO / "index.html").read_text(encoding="utf-8")
        self.assertIn('id="checkUpdate"', html)
        self.assertIn('id="installUpdate"', html)
        self.assertNotIn('id="updateToken"', html)
        self.assertIn("/api/update/check", html)
        self.assertIn("/api/update/install", html)
        self.assertNotIn("更新包由 Flow Factory", html)
        self.assertIn("flowfactory update", html)
        self.assertIn("loadAutostart();loadLanAccess();checkForUpdate();loadSettingsFile", html)
        self.assertIn("settings-status update-available", html)
        self.assertIn('id="factoryVersion"', html)
        self.assertIn('id="factoryUpdateBtn"', html)
        self.assertIn("`当前版本：v${version}${liveConfig.managed_install?'':'（開發版）'}`", html)
        self.assertIn("`v${current}${managed?'':'（開發版）'}`", html)
        self.assertIn('data-settings-nav="system"', html)
        self.assertIn('data-settings-panel="system"', html)
        self.assertIn('data-theme-choice="dark"', html)
        self.assertIn('function saveTheme(theme)', html)
        self.assertIn("await loadAppSettings();renderFactoryVersion", html)
        self.assertIn("function checkSidebarUpdate()", html)
        self.assertIn("installUpdateFromSidebar", html)
        self.assertIn("await checkForUpdate();if(updateAvailable)installUpdate()", html)
        self.assertIn("checkSidebarUpdate()", html)

    def test_settings_page_exposes_autostart_toggle(self):
        html = (REPO / "index.html").read_text(encoding="utf-8")
        self.assertIn('id="autostartToggle"', html)
        self.assertIn("/api/autostart", html)
        self.assertIn("不会自动弹出浏览器", html)

    def test_dark_theme_covers_secondary_application_surfaces(self):
        html = (REPO / "index.html").read_text(encoding="utf-8")
        self.assertIn("Complete dark theme coverage", html)
        self.assertIn('html[data-theme="dark"] #flowDialog.ff7-dialog', html)
        self.assertIn('html[data-theme="dark"] .agent-chat-context', html)
        self.assertIn('html[data-theme="dark"] .ai-json-review', html)
        self.assertIn('html[data-theme="dark"] .market-list-pane', html)
        self.assertIn('html[data-theme="dark"] .markdown-preview', html)
        self.assertIn('html[data-theme="dark"] #addFactoryBtn', html)
        self.assertIn('html[data-theme="dark"] #licenseDialog', html)
        self.assertIn('html[data-theme="dark"] .store-dialog', html)
        self.assertIn("function initUnifiedScrollSurfaces()", html)
        self.assertIn("setTimeout(()=>element.classList.remove('ff-scroll-active'),2000)", html)
        self.assertIn("ff-edge-top", html)
        self.assertIn("ff-edge-bottom", html)
        self.assertIn("element.closest('#flowDialog')", html)
        self.assertIn('.icon-btn[data-close-dialog]', html)
        self.assertIn('html[data-theme="dark"] .nav-item .factory-actions .mini-icon-btn', html)

    def test_license_ui_and_server_enforcement_are_present(self):
        html = (REPO / "index.html").read_text(encoding="utf-8")
        server = (REPO / "server.py").read_text(encoding="utf-8")
        self.assertIn('id="licenseBtn"', html)
        self.assertIn('id="licenseDialog"', html)
        self.assertIn("🔑 解鎖「流程工廠」", html)
        self.assertNotIn("AutoMoney 私享會授權", html)
        self.assertNotIn("免費版", html)
        self.assertNotIn("月費版", html)
        self.assertNotIn("終身版", html)
        self.assertIn("gda_master", html)
        self.assertIn("付款後自動發送授權碼", html)
        self.assertIn("https://www.patreon.com/cw/u109401811/membership", html)
        self.assertIn("https://www.ifdian.net/item/c684fe7486ae11f19afb5254001e7c00", html)
        self.assertIn("早期版本方案", html)
        self.assertIn("目前方案", html)
        self.assertIn("訂閱｜Patreon", html)
        self.assertIn("訂閱｜愛發電", html)
        self.assertIn("payment-logo-card", html)
        self.assertIn("payment-logo-ifdian", html)
        self.assertIn("正式版上線後開放", html)
        self.assertIn("試用狀態只能使用一個工作流工廠", html)
        self.assertIn("licenseState.licensed?openFactoryDialog():openLicenseDialog", html)
        self.assertIn("licensing.limit_workflows", server)
        self.assertIn("/api/license/activate", server)
        self.assertIn("Allow writes for all users; display limits are enforced by the frontend.", server)
        self.assertIn("_rotate_workflows_backups", server)
        self.assertIn("/api/license?refresh=", html)
        self.assertIn("await loadLicense(false)", html)
        self.assertIn("refreshLicenseInBackground", html)
        self.assertIn("get('refresh', ['1'])", server)

    def test_admin_license_generator_uses_macos_keychain(self):
        command = (REPO / "scripts" / "create-license.command").read_text(encoding="utf-8")
        admin = (REPO / "scripts" / "license_admin.py").read_text(encoding="utf-8")
        page = (REPO / "scripts" / "license_admin.html").read_text(encoding="utf-8")
        self.assertIn("license_admin.py", command)
        self.assertIn("security", admin)
        self.assertIn("127.0.0.1", admin)
        self.assertIn("X-Admin-Session", admin)
        self.assertIn("创建授权码", page)
        self.assertIn("重置设备", page)
        self.assertIn("保存调整", page)
        self.assertIn("stop_previous_instance", admin)
        self.assertIn("FLOWFACTORY_LICENSE_ADMIN_PORT", admin)
        self.assertIn('"--noproxy", "*", "--ipv4"', admin)
        self.assertIn('"--connect-timeout", "5", "--max-time", "15"', admin)
        self.assertIn('input=f\'header = "Authorization: Bearer {escaped_token}"', admin)
        self.assertNotIn("urllib.request", admin)
        self.assertIn("读取失败", page)
        self.assertIn('class="spinner"', page)
        self.assertIn("正在连接云端授权服务", page)
        self.assertIn("document.execCommand('copy')", page)
        self.assertIn("授权码已成功创建", page)
        self.assertIn("月费授权从客户首次启用时开始计算", page)
        self.assertIn("首次启用后的有效月数", page)
        self.assertIn("首次启用后计算", page)
        self.assertIn("body.duration_months=Number(months.value)", page)
        self.assertIn("浏览器未允许自动复制", page)
        self.assertIn('id="createMonthsRow"', page)
        self.assertIn("function syncCreatePlan()", page)
        self.assertIn("createMonthsRow.hidden=!monthly", page)
        self.assertIn("months.disabled=!monthly", page)
        self.assertIn('id="createProgress" hidden', page)
        self.assertIn(".loading[hidden]{display:none}", page)
        self.assertIn("if(creatingLicenses)return", page)
        self.assertIn("正在一次建立", page)
        self.assertIn("controller.abort(),75000", page)
        self.assertIn("已自动解除按钮锁定", page)
        self.assertNotIn("for _ in range(count)", admin)
        self.assertIn('parsed.path=="/api/install-stats"', admin)
        self.assertIn('parsed.path=="/api/install-events"', admin)
        self.assertIn("安装与更新统计", page)
        self.assertIn("累计安装设备", page)
        self.assertIn("loadInstallStats", page)
        self.assertIn('id="licensePagination"', page)
        self.assertIn('id="pageSize"', page)
        self.assertIn('id="prevPage"', page)
        self.assertIn('id="nextPage"', page)
        self.assertIn('class="sortable" data-sort="created_at"', page)
        self.assertIn("function renderLicenses()", page)
        self.assertIn("licenseSortDirection", page)
        self.assertIn('id="eventPagination"', page)
        self.assertIn('id="eventPageSize"', page)
        self.assertIn("function loadInstallEvents()", page)
        self.assertIn("page_size:licensePageSize", page)
        self.assertIn("page_size:eventPageSizeValue", page)

    def test_uninstaller_removes_launch_agent(self):
        uninstaller = (REPO / "scripts" / "uninstall.sh").read_text(encoding="utf-8")
        self.assertIn("com.gda.flowfactory.plist", uninstaller)
        self.assertIn('launchctl bootout "gui/$(id -u)/com.gda.flowfactory"', uninstaller)


if __name__ == "__main__":
    unittest.main()
